import type { AppLocale } from '@partokens/i18n'

export type AuthPrototypeCopy = {
  rail: {
    body: string
    path: [string, string, string]
    accountTitle: string
    pricingBody: string
    privacyBody: string
    support: string
  }
  consentLead: string
  passwordHint: string
  showPassword: string
  hidePassword: string
  signinBody: string
  signupBody: string
  verifyTitle: string
  verifyBody: string
  verifySent: string
  forgotBody: string
  resetBody: string
  resetResultBody: string
  passwordCopied: string
  oauthBody: string
  oauthReadyTitle: string
  oauthReadyBody: string
  oauthRouteLabel: string
  oauthRouteValue: string
  oauthReadyStatus: string
  oauthContinue: string
  otpBody: string
  backupBody: string
  useBackup: string
  useAuthenticator: string
  backupLabel: string
}

export const authPrototypeCopy: Record<AppLocale, AuthPrototypeCopy> = {
  'zh-CN': {
    rail: {
      body: '身份验证只负责建立账户会话。进入后再加载你的模型、价格与用量。',
      path: ['身份', '会话', '工作区'],
      accountTitle: '账户数据',
      pricingBody: '模型、价格和账户额度仅在登录后读取。',
      privacyBody: '本地对话记录不会作为登录数据上传。',
      support: '账户访问遇到问题时，可联系支持团队。',
    },
    consentLead: '我已阅读并同意以下条款：',
    passwordHint: '至少 8 个字符，建议使用独立密码。',
    showPassword: '显示密码',
    hidePassword: '隐藏密码',
    signinBody: '使用账户密码继续。邮箱验证码仅用于注册和账户绑定。',
    signupBody: '创建账户，并在服务要求时完成邮箱验证。',
    verifyTitle: '验证邮箱',
    verifyBody: '输入发送到邮箱的验证码，完成注册联系方式验证。',
    verifySent: '验证码已发送，请检查收件箱。',
    forgotBody: '输入注册邮箱，获取一次性密码重置链接。',
    resetBody: '确认重置链接后，系统将生成新的账户密码。',
    resetResultBody: '新密码仅在当前页面完整显示一次，请立即保存。',
    passwordCopied: '密码已复制。',
    oauthBody: '正在验证登录提供商返回的信息，并确认账户角色。',
    oauthReadyTitle: '登录已确认',
    oauthReadyBody: '提供商响应和账户路由已确认，可以进入工作区。',
    oauthRouteLabel: '账户路由',
    oauthRouteValue: '用户工作区',
    oauthReadyStatus: '登录响应已确认，账户会话可以继续。',
    oauthContinue: '进入工作区',
    otpBody: '输入验证器代码或备用码，完成本次登录。',
    backupBody: '每个备用码只能使用一次。验证后该码将失效。',
    useBackup: '改用备用码',
    useAuthenticator: '改用验证器代码',
    backupLabel: '备用码',
  },
  'zh-TW': {
    rail: {
      body: '身分驗證只負責建立帳戶工作階段。進入後才載入你的模型、價格與用量。',
      path: ['身分', '工作階段', '工作區'],
      accountTitle: '帳戶資料',
      pricingBody: '模型、價格與帳戶額度只會在登入後讀取。',
      privacyBody: '本機對話記錄不會作為登入資料上傳。',
      support: '帳戶存取遇到問題時，可聯絡支援團隊。',
    },
    consentLead: '我已閱讀並同意以下條款：',
    passwordHint: '至少 8 個字元，建議使用獨立密碼。',
    showPassword: '顯示密碼',
    hidePassword: '隱藏密碼',
    signinBody: '使用帳戶密碼繼續。電子郵件驗證碼只用於註冊與帳戶綁定。',
    signupBody: '建立帳戶，並在服務要求時完成電子郵件驗證。',
    verifyTitle: '驗證電子郵件',
    verifyBody: '輸入寄送到電子郵件的驗證碼，完成註冊聯絡方式驗證。',
    verifySent: '驗證碼已寄出，請查看收件匣。',
    forgotBody: '輸入註冊電子郵件，取得一次性密碼重設連結。',
    resetBody: '確認重設連結後，系統會產生新的帳戶密碼。',
    resetResultBody: '新密碼只會在此頁完整顯示一次，請立即保存。',
    passwordCopied: '密碼已複製。',
    oauthBody: '正在驗證登入供應商傳回的資訊，並確認帳戶角色。',
    oauthReadyTitle: '登入已確認',
    oauthReadyBody: '供應商回應與帳戶路由已確認，可以進入工作區。',
    oauthRouteLabel: '帳戶路由',
    oauthRouteValue: '使用者工作區',
    oauthReadyStatus: '登入回應已確認，帳戶工作階段可以繼續。',
    oauthContinue: '進入工作區',
    otpBody: '輸入驗證器代碼或備用碼，完成本次登入。',
    backupBody: '每個備用碼只能使用一次，驗證後即失效。',
    useBackup: '改用備用碼',
    useAuthenticator: '改用驗證器代碼',
    backupLabel: '備用碼',
  },
  en: {
    rail: {
      body: 'Authentication establishes the account session. Your models, pricing, and usage load only after access is confirmed.',
      path: ['Identity', 'Session', 'Workspace'],
      accountTitle: 'Account data',
      pricingBody: 'Models, pricing, and account quota are read only after sign-in.',
      privacyBody: 'Local conversation history is not uploaded as sign-in data.',
      support: 'Contact support if you cannot access your account.',
    },
    consentLead: 'I have read and agree to:',
    passwordHint: 'Use at least 8 characters and a password unique to this account.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    signinBody: 'Continue with your account password. Email codes are only for registration and account binding.',
    signupBody: 'Create an account and verify your email when the service requires it.',
    verifyTitle: 'Verify your email',
    verifyBody: 'Enter the code sent to your email to verify the contact address for registration.',
    verifySent: 'Verification code sent. Check your inbox.',
    forgotBody: 'Enter the registered email to receive a one-time password reset link.',
    resetBody: 'After the reset link is confirmed, the service will issue a new account password.',
    resetResultBody: 'The full new password is shown only once on this page. Store it now.',
    passwordCopied: 'Password copied.',
    oauthBody: 'The provider response is being verified before the account role is resolved.',
    oauthReadyTitle: 'Sign-in confirmed',
    oauthReadyBody: 'The provider response and account route are confirmed. The workspace is ready.',
    oauthRouteLabel: 'Account route',
    oauthRouteValue: 'User workspace',
    oauthReadyStatus: 'The sign-in response is confirmed and the account session can continue.',
    oauthContinue: 'Enter workspace',
    otpBody: 'Enter an authenticator code or backup code to finish signing in.',
    backupBody: 'Each backup code works once and becomes invalid after verification.',
    useBackup: 'Use a backup code',
    useAuthenticator: 'Use an authenticator code',
    backupLabel: 'Backup code',
  },
  ja: {
    rail: {
      body: '認証はアカウントセッションの確立だけを行います。モデル、料金、使用量はログイン後に読み込みます。',
      path: ['本人確認', 'セッション', 'ワークスペース'],
      accountTitle: 'アカウントデータ',
      pricingBody: 'モデル、料金、アカウントのクォータはログイン後にのみ取得します。',
      privacyBody: 'ローカルの会話履歴がログイン情報として送信されることはありません。',
      support: 'アカウントにアクセスできない場合はサポートへお問い合わせください。',
    },
    consentLead: '以下を読み、同意します：',
    passwordHint: '8 文字以上で、このアカウント専用のパスワードを使用してください。',
    showPassword: 'パスワードを表示',
    hidePassword: 'パスワードを隠す',
    signinBody: 'アカウントのパスワードで続行します。メールコードは登録とアカウント連携にのみ使用します。',
    signupBody: 'アカウントを作成し、必要な場合はメール認証を完了します。',
    verifyTitle: 'メールを確認',
    verifyBody: 'メールに届いたコードを入力し、登録用の連絡先を確認してください。',
    verifySent: '確認コードを送信しました。受信トレイを確認してください。',
    forgotBody: '登録済みメールを入力して、一度限りのパスワード再設定リンクを受け取ります。',
    resetBody: '再設定リンクを確認すると、新しいアカウントパスワードが発行されます。',
    resetResultBody: '新しいパスワードの全文表示はこのページで一度だけです。今すぐ保存してください。',
    passwordCopied: 'パスワードをコピーしました。',
    oauthBody: 'プロバイダーの応答を確認し、アカウント権限を判定しています。',
    oauthReadyTitle: 'ログインを確認しました',
    oauthReadyBody: 'プロバイダーの応答とアカウントの移動先を確認しました。ワークスペースを開けます。',
    oauthRouteLabel: 'アカウントの移動先',
    oauthRouteValue: 'ユーザーワークスペース',
    oauthReadyStatus: 'ログイン応答を確認し、アカウントセッションを続行できます。',
    oauthContinue: 'ワークスペースへ',
    otpBody: '認証コードまたはバックアップコードを入力してログインを完了します。',
    backupBody: '各バックアップコードは一度だけ使用でき、確認後は無効になります。',
    useBackup: 'バックアップコードを使用',
    useAuthenticator: '認証コードを使用',
    backupLabel: 'バックアップコード',
  },
  ru: {
    rail: {
      body: 'Проверка личности создаёт только сеанс аккаунта. Модели, цены и расход загружаются после входа.',
      path: ['Личность', 'Сеанс', 'Рабочая область'],
      accountTitle: 'Данные аккаунта',
      pricingBody: 'Модели, цены и квота аккаунта загружаются только после входа.',
      privacyBody: 'Локальная история чатов не отправляется как часть данных для входа.',
      support: 'Если доступ к аккаунту не работает, обратитесь в поддержку.',
    },
    consentLead: 'Я прочитал(а) и принимаю:',
    passwordHint: 'Не менее 8 символов; используйте отдельный пароль для этого аккаунта.',
    showPassword: 'Показать пароль',
    hidePassword: 'Скрыть пароль',
    signinBody: 'Продолжите с паролем аккаунта. Коды из писем используются только для регистрации и привязки.',
    signupBody: 'Создайте аккаунт и подтвердите почту, если этого требует сервис.',
    verifyTitle: 'Подтвердите почту',
    verifyBody: 'Введите код из письма, чтобы подтвердить контактный адрес для регистрации.',
    verifySent: 'Код отправлен. Проверьте входящие сообщения.',
    forgotBody: 'Введите зарегистрированную почту, чтобы получить одноразовую ссылку сброса пароля.',
    resetBody: 'После подтверждения ссылки сервис выдаст новый пароль аккаунта.',
    resetResultBody: 'Полный новый пароль показывается на этой странице один раз. Сохраните его сейчас.',
    passwordCopied: 'Пароль скопирован.',
    oauthBody: 'Ответ провайдера проверяется перед определением роли аккаунта.',
    oauthReadyTitle: 'Вход подтверждён',
    oauthReadyBody: 'Ответ провайдера и маршрут аккаунта подтверждены. Рабочая область готова.',
    oauthRouteLabel: 'Маршрут аккаунта',
    oauthRouteValue: 'Рабочая область',
    oauthReadyStatus: 'Ответ для входа подтверждён, сеанс аккаунта можно продолжить.',
    oauthContinue: 'Войти в рабочую область',
    otpBody: 'Введите код приложения или резервный код, чтобы завершить вход.',
    backupBody: 'Каждый резервный код действует один раз и станет недействительным после проверки.',
    useBackup: 'Использовать резервный код',
    useAuthenticator: 'Использовать код приложения',
    backupLabel: 'Резервный код',
  },
  fr: {
    rail: {
      body: 'L’authentification établit uniquement la session du compte. Les modèles, tarifs et usages sont chargés après validation.',
      path: ['Identité', 'Session', 'Espace de travail'],
      accountTitle: 'Données du compte',
      pricingBody: 'Les modèles, tarifs et quotas du compte sont lus uniquement après connexion.',
      privacyBody: 'L’historique local des conversations n’est pas transmis comme donnée de connexion.',
      support: 'Contactez l’assistance si vous ne pouvez pas accéder à votre compte.',
    },
    consentLead: 'J’ai lu et j’accepte :',
    passwordHint: 'Utilisez au moins 8 caractères et un mot de passe propre à ce compte.',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    signinBody: 'Continuez avec le mot de passe du compte. Les codes e-mail servent uniquement à l’inscription et aux liaisons.',
    signupBody: 'Créez un compte et vérifiez votre adresse e-mail lorsque le service l’exige.',
    verifyTitle: 'Vérifiez votre adresse e-mail',
    verifyBody: 'Saisissez le code reçu par e-mail pour confirmer l’adresse de contact de l’inscription.',
    verifySent: 'Code envoyé. Consultez votre boîte de réception.',
    forgotBody: 'Saisissez l’adresse enregistrée pour recevoir un lien unique de réinitialisation.',
    resetBody: 'Après validation du lien, le service génère un nouveau mot de passe pour le compte.',
    resetResultBody: 'Le nouveau mot de passe complet n’est affiché qu’une fois sur cette page. Enregistrez-le maintenant.',
    passwordCopied: 'Mot de passe copié.',
    oauthBody: 'La réponse du fournisseur est vérifiée avant de déterminer le rôle du compte.',
    oauthReadyTitle: 'Connexion confirmée',
    oauthReadyBody: 'La réponse du fournisseur et la destination du compte sont confirmées. L’espace de travail est prêt.',
    oauthRouteLabel: 'Destination du compte',
    oauthRouteValue: 'Espace de travail',
    oauthReadyStatus: 'La réponse de connexion est confirmée et la session du compte peut continuer.',
    oauthContinue: 'Ouvrir l’espace de travail',
    otpBody: 'Saisissez un code d’authentification ou de secours pour terminer la connexion.',
    backupBody: 'Chaque code de secours est à usage unique et devient invalide après vérification.',
    useBackup: 'Utiliser un code de secours',
    useAuthenticator: 'Utiliser le code d’authentification',
    backupLabel: 'Code de secours',
  },
  vi: {
    rail: {
      body: 'Xác thực chỉ thiết lập phiên tài khoản. Mô hình, giá và mức sử dụng được tải sau khi quyền truy cập được xác nhận.',
      path: ['Danh tính', 'Phiên', 'Không gian làm việc'],
      accountTitle: 'Dữ liệu tài khoản',
      pricingBody: 'Mô hình, giá và hạn mức tài khoản chỉ được đọc sau khi đăng nhập.',
      privacyBody: 'Lịch sử trò chuyện cục bộ không được tải lên như dữ liệu đăng nhập.',
      support: 'Liên hệ hỗ trợ nếu bạn không thể truy cập tài khoản.',
    },
    consentLead: 'Tôi đã đọc và đồng ý với:',
    passwordHint: 'Dùng ít nhất 8 ký tự và một mật khẩu riêng cho tài khoản này.',
    showPassword: 'Hiện mật khẩu',
    hidePassword: 'Ẩn mật khẩu',
    signinBody: 'Tiếp tục bằng mật khẩu tài khoản. Mã email chỉ dùng cho đăng ký và liên kết tài khoản.',
    signupBody: 'Tạo tài khoản và xác minh email khi dịch vụ yêu cầu.',
    verifyTitle: 'Xác minh email',
    verifyBody: 'Nhập mã được gửi tới email để xác minh địa chỉ liên hệ đăng ký.',
    verifySent: 'Đã gửi mã xác minh. Hãy kiểm tra hộp thư đến.',
    forgotBody: 'Nhập email đã đăng ký để nhận liên kết đặt lại mật khẩu dùng một lần.',
    resetBody: 'Sau khi liên kết được xác nhận, dịch vụ sẽ cấp mật khẩu tài khoản mới.',
    resetResultBody: 'Mật khẩu mới đầy đủ chỉ hiển thị một lần trên trang này. Hãy lưu ngay.',
    passwordCopied: 'Đã sao chép mật khẩu.',
    oauthBody: 'Phản hồi của nhà cung cấp đang được xác minh trước khi xác định vai trò tài khoản.',
    oauthReadyTitle: 'Đã xác nhận đăng nhập',
    oauthReadyBody: 'Phản hồi của nhà cung cấp và tuyến tài khoản đã được xác nhận. Không gian làm việc đã sẵn sàng.',
    oauthRouteLabel: 'Tuyến tài khoản',
    oauthRouteValue: 'Không gian làm việc',
    oauthReadyStatus: 'Phản hồi đăng nhập đã được xác nhận và phiên tài khoản có thể tiếp tục.',
    oauthContinue: 'Vào không gian làm việc',
    otpBody: 'Nhập mã xác thực hoặc mã dự phòng để hoàn tất đăng nhập.',
    backupBody: 'Mỗi mã dự phòng chỉ dùng một lần và sẽ hết hiệu lực sau khi xác minh.',
    useBackup: 'Dùng mã dự phòng',
    useAuthenticator: 'Dùng mã xác thực',
    backupLabel: 'Mã dự phòng',
  },
}
