import type { AppLocale } from '@partokens/i18n'

const consoleDataCopy: Record<AppLocale, Record<string, string>> = {
  'zh-CN': {
    'View all': '查看全部',
    'Time range': '时间范围',
    Granularity: '粒度',
    Measure: '指标',
    'Current period': '本周期',
    'Previous period': '上一周期',
    'View chart data': '查看图表数据',
    'Success rate': '成功率',
    'Key created': '密钥已创建',
    Expiry: '有效期',
    Copied: '已复制',
    'This action cannot be undone.': '此操作无法撤销。',
    'Changes saved': '更改已保存',
    Logs: '日志',
  },
  'zh-TW': {
    'View all': '查看全部',
    'Time range': '時間範圍',
    Granularity: '粒度',
    Measure: '指標',
    'Current period': '本期',
    'Previous period': '上期',
    'View chart data': '查看圖表資料',
    'Success rate': '成功率',
    'Key created': '金鑰已建立',
    Expiry: '有效期限',
    Copied: '已複製',
    'This action cannot be undone.': '此操作無法復原。',
    'Changes saved': '變更已儲存',
    Logs: '記錄',
  },
  en: {
    'View all': 'View all',
    'Time range': 'Time range',
    Granularity: 'Granularity',
    Measure: 'Measure',
    'Current period': 'Current period',
    'Previous period': 'Previous period',
    'View chart data': 'View chart data',
    'Success rate': 'Success rate',
    'Key created': 'Key created',
    Expiry: 'Expiry',
    Copied: 'Copied',
    'This action cannot be undone.': 'This action cannot be undone.',
    'Changes saved': 'Changes saved',
    Logs: 'Logs',
  },
  ja: {
    'View all': 'すべて表示',
    'Time range': '期間',
    Granularity: '粒度',
    Measure: '指標',
    'Current period': '現在の期間',
    'Previous period': '前の期間',
    'View chart data': 'グラフデータを表示',
    'Success rate': '成功率',
    'Key created': 'キーを作成しました',
    Expiry: '有効期限',
    Copied: 'コピーしました',
    'This action cannot be undone.': 'この操作は元に戻せません。',
    'Changes saved': '変更を保存しました',
    Logs: 'ログ',
  },
  ru: {
    'View all': 'Показать все',
    'Time range': 'Период',
    Granularity: 'Детализация',
    Measure: 'Показатель',
    'Current period': 'Текущий период',
    'Previous period': 'Предыдущий период',
    'View chart data': 'Показать данные графика',
    'Success rate': 'Доля успешных запросов',
    'Key created': 'Ключ создан',
    Expiry: 'Срок действия',
    Copied: 'Скопировано',
    'This action cannot be undone.': 'Это действие нельзя отменить.',
    'Changes saved': 'Изменения сохранены',
    Logs: 'Журнал',
  },
  fr: {
    'View all': 'Tout afficher',
    'Time range': 'Période',
    Granularity: 'Granularité',
    Measure: 'Indicateur',
    'Current period': 'Période actuelle',
    'Previous period': 'Période précédente',
    'View chart data': 'Afficher les données du graphique',
    'Success rate': 'Taux de réussite',
    'Key created': 'Clé créée',
    Expiry: 'Expiration',
    Copied: 'Copié',
    'This action cannot be undone.': 'Cette action est irréversible.',
    'Changes saved': 'Modifications enregistrées',
    Logs: 'Journaux',
  },
  vi: {
    'View all': 'Xem tất cả',
    'Time range': 'Khoảng thời gian',
    Granularity: 'Mức chi tiết',
    Measure: 'Chỉ số',
    'Current period': 'Kỳ hiện tại',
    'Previous period': 'Kỳ trước',
    'View chart data': 'Xem dữ liệu biểu đồ',
    'Success rate': 'Tỷ lệ thành công',
    'Key created': 'Đã tạo khóa',
    Expiry: 'Hết hạn',
    Copied: 'Đã sao chép',
    'This action cannot be undone.': 'Không thể hoàn tác thao tác này.',
    'Changes saved': 'Đã lưu thay đổi',
    Logs: 'Nhật ký',
  },
}

export function translateConsoleData(locale: AppLocale, key: string) {
  return consoleDataCopy[locale][key] ?? key
}
