import type { AppLocale } from '@partokens/i18n'

const zhCN = {
  'Billing route': '余额路径',
  'See how a configured amount changes from selection to account balance.': '查看固定金额如何经过优惠与支付，最终进入账户余额。',
  'Configured amount': '固定金额',
  'Resulting balance': '到账后余额',
  'Account center': '账户中心',
  'Account trust': '账户保护状态',
  'Keep identity, recovery, and sign-in protection visible in one route.': '在一条路径中查看身份、恢复方式与登录保护状态。',
  'Identity ready': '身份已确认',
  'Recovery ready': '恢复方式已就绪',
  'Protection available': '可继续加强保护',
  'Edit the information people see without exposing internal account identifiers.': '编辑对外显示的信息，不暴露内部账户标识。',
  'Manage passwords and stronger sign-in methods from one security surface.': '集中管理密码与更强的登录验证方式。',
  'Review the services that can sign in to this account.': '查看可用于登录此账户的邮箱与外部服务。',
  'Choose where balance alerts arrive and how private request data is handled.': '选择余额提醒的接收方式，并控制私有请求数据的处理方式。',
  'Profile details': '资料详情',
  'Check-in activity': '签到动态',
  'Connected sign-in methods': '已连接的登录方式',
  'Security methods': '安全方式',
  'Private behavior': '隐私与行为',
  'Active plan': '生效中的方案',
  'Current route': '当前扣费路径',
  'No custom amount entry is available.': '不提供自定义金额输入。',
  'Payment preview': '支付预览',
  'Demo interaction': '演示交互',
  'Ready to protect': '可启用保护',
  Updated: '已更新',
  Generated: '已生成',
  Copied: '已复制',
  Disconnected: '已断开连接',
  Connections: '账号连接',
  Success: '成功',
} as const

type AccountCopyKey = keyof typeof zhCN

const packs: Record<AppLocale, Record<AccountCopyKey, string>> = {
  'zh-CN': zhCN,
  'zh-TW': {
    'Billing route': '餘額路徑',
    'See how a configured amount changes from selection to account balance.': '查看固定金額如何經過優惠與付款，最終進入帳戶餘額。',
    'Configured amount': '固定金額',
    'Resulting balance': '入帳後餘額',
    'Account center': '帳戶中心',
    'Account trust': '帳戶保護狀態',
    'Keep identity, recovery, and sign-in protection visible in one route.': '在一條路徑中查看身分、復原方式與登入保護狀態。',
    'Identity ready': '身分已確認',
    'Recovery ready': '復原方式已就緒',
    'Protection available': '可繼續加強保護',
    'Edit the information people see without exposing internal account identifiers.': '編輯對外顯示的資訊，不暴露內部帳戶識別碼。',
    'Manage passwords and stronger sign-in methods from one security surface.': '集中管理密碼與更強的登入驗證方式。',
    'Review the services that can sign in to this account.': '查看可用於登入此帳戶的電子郵件與外部服務。',
    'Choose where balance alerts arrive and how private request data is handled.': '選擇餘額提醒的接收方式，並控制私人請求資料的處理方式。',
    'Profile details': '資料詳情',
    'Check-in activity': '簽到動態',
    'Connected sign-in methods': '已連接的登入方式',
    'Security methods': '安全方式',
    'Private behavior': '隱私與行為',
    'Active plan': '生效中的方案',
    'Current route': '目前扣費路徑',
    'No custom amount entry is available.': '不提供自訂金額輸入。',
    'Payment preview': '付款預覽',
    'Demo interaction': '示範互動',
    'Ready to protect': '可啟用保護',
    Updated: '已更新',
    Generated: '已產生',
    Copied: '已複製',
    Disconnected: '已中斷連接',
    Connections: '帳號連接',
    Success: '成功',
  },
  en: {
    'Billing route': 'Billing route',
    'See how a configured amount changes from selection to account balance.': 'See how a configured amount changes from selection to account balance.',
    'Configured amount': 'Configured amount',
    'Resulting balance': 'Resulting balance',
    'Account center': 'Account center',
    'Account trust': 'Account trust',
    'Keep identity, recovery, and sign-in protection visible in one route.': 'Keep identity, recovery, and sign-in protection visible in one route.',
    'Identity ready': 'Identity ready',
    'Recovery ready': 'Recovery ready',
    'Protection available': 'Protection available',
    'Edit the information people see without exposing internal account identifiers.': 'Edit the information people see without exposing internal account identifiers.',
    'Manage passwords and stronger sign-in methods from one security surface.': 'Manage passwords and stronger sign-in methods from one security surface.',
    'Review the services that can sign in to this account.': 'Review the services that can sign in to this account.',
    'Choose where balance alerts arrive and how private request data is handled.': 'Choose where balance alerts arrive and how private request data is handled.',
    'Profile details': 'Profile details',
    'Check-in activity': 'Check-in activity',
    'Connected sign-in methods': 'Connected sign-in methods',
    'Security methods': 'Security methods',
    'Private behavior': 'Private behavior',
    'Active plan': 'Active plan',
    'Current route': 'Current route',
    'No custom amount entry is available.': 'No custom amount entry is available.',
    'Payment preview': 'Payment preview',
    'Demo interaction': 'Demo interaction',
    'Ready to protect': 'Ready to protect',
    Updated: 'Updated',
    Generated: 'Generated',
    Copied: 'Copied',
    Disconnected: 'Disconnected',
    Connections: 'Connections',
    Success: 'Success',
  },
  ja: {
    'Billing route': '残高ルート',
    'See how a configured amount changes from selection to account balance.': '設定済み金額が割引と支払いを経て残高に反映される流れを確認できます。',
    'Configured amount': '設定済み金額',
    'Resulting balance': '反映後の残高',
    'Account center': 'アカウントセンター',
    'Account trust': 'アカウント保護状態',
    'Keep identity, recovery, and sign-in protection visible in one route.': '本人情報、復旧手段、ログイン保護を一つの流れで確認できます。',
    'Identity ready': '本人情報を確認済み',
    'Recovery ready': '復旧手段を設定済み',
    'Protection available': '保護を強化できます',
    'Edit the information people see without exposing internal account identifiers.': '内部アカウント識別子を表示せず、公開情報を編集します。',
    'Manage passwords and stronger sign-in methods from one security surface.': 'パスワードと強固なログイン方法を一つの画面で管理します。',
    'Review the services that can sign in to this account.': 'このアカウントへのログインに使えるサービスを確認します。',
    'Choose where balance alerts arrive and how private request data is handled.': '残高通知の送信先と非公開リクエストデータの扱いを選択します。',
    'Profile details': 'プロフィール詳細',
    'Check-in activity': 'チェックイン履歴',
    'Connected sign-in methods': '連携済みログイン方法',
    'Security methods': 'セキュリティ方法',
    'Private behavior': 'プライバシーと動作',
    'Active plan': '利用中のプラン',
    'Current route': '現在の課金ルート',
    'No custom amount entry is available.': '任意金額の入力には対応していません。',
    'Payment preview': '支払いプレビュー',
    'Demo interaction': 'デモ操作',
    'Ready to protect': '保護を有効化できます',
    Updated: '更新しました',
    Generated: '生成しました',
    Copied: 'コピーしました',
    Disconnected: '連携を解除しました',
    Connections: 'アカウント連携',
    Success: '成功',
  },
  ru: {
    'Billing route': 'Маршрут баланса',
    'See how a configured amount changes from selection to account balance.': 'Проследите путь заданной суммы от выбора и скидки до баланса аккаунта.',
    'Configured amount': 'Заданная сумма',
    'Resulting balance': 'Итоговый баланс',
    'Account center': 'Центр аккаунта',
    'Account trust': 'Защита аккаунта',
    'Keep identity, recovery, and sign-in protection visible in one route.': 'Контролируйте личность, восстановление и защиту входа в одной цепочке.',
    'Identity ready': 'Личность подтверждена',
    'Recovery ready': 'Восстановление настроено',
    'Protection available': 'Защиту можно усилить',
    'Edit the information people see without exposing internal account identifiers.': 'Редактируйте видимые данные, не раскрывая внутренние идентификаторы аккаунта.',
    'Manage passwords and stronger sign-in methods from one security surface.': 'Управляйте паролем и усиленными способами входа в одном разделе.',
    'Review the services that can sign in to this account.': 'Проверьте сервисы, через которые можно войти в аккаунт.',
    'Choose where balance alerts arrive and how private request data is handled.': 'Выберите канал уведомлений о балансе и правила для приватных данных запросов.',
    'Profile details': 'Данные профиля',
    'Check-in activity': 'История отметок',
    'Connected sign-in methods': 'Подключённые способы входа',
    'Security methods': 'Способы защиты',
    'Private behavior': 'Приватность и поведение',
    'Active plan': 'Активный план',
    'Current route': 'Текущий порядок списания',
    'No custom amount entry is available.': 'Произвольную сумму ввести нельзя.',
    'Payment preview': 'Предпросмотр платежа',
    'Demo interaction': 'Демонстрация',
    'Ready to protect': 'Защиту можно включить',
    Updated: 'Обновлено',
    Generated: 'Создано',
    Copied: 'Скопировано',
    Disconnected: 'Отключено',
    Connections: 'Подключения',
    Success: 'Успешно',
  },
  fr: {
    'Billing route': 'Parcours du solde',
    'See how a configured amount changes from selection to account balance.': 'Suivez un montant configuré, de la sélection au solde après remise et paiement.',
    'Configured amount': 'Montant configuré',
    'Resulting balance': 'Solde après recharge',
    'Account center': 'Centre du compte',
    'Account trust': 'Protection du compte',
    'Keep identity, recovery, and sign-in protection visible in one route.': 'Suivez l’identité, la récupération et la protection de connexion sur un même parcours.',
    'Identity ready': 'Identité vérifiée',
    'Recovery ready': 'Récupération prête',
    'Protection available': 'Protection à renforcer',
    'Edit the information people see without exposing internal account identifiers.': 'Modifiez les informations visibles sans exposer les identifiants internes du compte.',
    'Manage passwords and stronger sign-in methods from one security surface.': 'Gérez le mot de passe et les méthodes de connexion renforcées au même endroit.',
    'Review the services that can sign in to this account.': 'Vérifiez les services autorisés à se connecter à ce compte.',
    'Choose where balance alerts arrive and how private request data is handled.': 'Choisissez où recevoir les alertes de solde et comment traiter les données privées des requêtes.',
    'Profile details': 'Détails du profil',
    'Check-in activity': 'Activité de pointage',
    'Connected sign-in methods': 'Méthodes de connexion liées',
    'Security methods': 'Méthodes de sécurité',
    'Private behavior': 'Confidentialité et comportement',
    'Active plan': 'Offre active',
    'Current route': 'Parcours de facturation actuel',
    'No custom amount entry is available.': 'La saisie d’un montant libre n’est pas disponible.',
    'Payment preview': 'Aperçu du paiement',
    'Demo interaction': 'Interaction de démonstration',
    'Ready to protect': 'Protection disponible',
    Updated: 'Mis à jour',
    Generated: 'Généré',
    Copied: 'Copié',
    Disconnected: 'Déconnecté',
    Connections: 'Connexions',
    Success: 'Réussi',
  },
  vi: {
    'Billing route': 'Luồng số dư',
    'See how a configured amount changes from selection to account balance.': 'Theo dõi số tiền cố định từ lúc chọn, áp dụng ưu đãi đến khi vào số dư.',
    'Configured amount': 'Số tiền cố định',
    'Resulting balance': 'Số dư sau nạp',
    'Account center': 'Trung tâm tài khoản',
    'Account trust': 'Mức bảo vệ tài khoản',
    'Keep identity, recovery, and sign-in protection visible in one route.': 'Theo dõi danh tính, khôi phục và bảo vệ đăng nhập trên cùng một luồng.',
    'Identity ready': 'Đã xác minh danh tính',
    'Recovery ready': 'Đã sẵn sàng khôi phục',
    'Protection available': 'Có thể tăng cường bảo vệ',
    'Edit the information people see without exposing internal account identifiers.': 'Chỉnh sửa thông tin hiển thị mà không để lộ mã định danh nội bộ.',
    'Manage passwords and stronger sign-in methods from one security surface.': 'Quản lý mật khẩu và phương thức đăng nhập mạnh hơn tại một nơi.',
    'Review the services that can sign in to this account.': 'Xem các dịch vụ có thể dùng để đăng nhập tài khoản này.',
    'Choose where balance alerts arrive and how private request data is handled.': 'Chọn nơi nhận cảnh báo số dư và cách xử lý dữ liệu yêu cầu riêng tư.',
    'Profile details': 'Chi tiết hồ sơ',
    'Check-in activity': 'Lịch sử điểm danh',
    'Connected sign-in methods': 'Phương thức đăng nhập đã kết nối',
    'Security methods': 'Phương thức bảo mật',
    'Private behavior': 'Quyền riêng tư và hành vi',
    'Active plan': 'Gói đang hoạt động',
    'Current route': 'Luồng tính phí hiện tại',
    'No custom amount entry is available.': 'Không hỗ trợ nhập số tiền tùy chỉnh.',
    'Payment preview': 'Xem trước thanh toán',
    'Demo interaction': 'Tương tác minh họa',
    'Ready to protect': 'Có thể bật bảo vệ',
    Updated: 'Đã cập nhật',
    Generated: 'Đã tạo',
    Copied: 'Đã sao chép',
    Disconnected: 'Đã ngắt kết nối',
    Connections: 'Kết nối',
    Success: 'Thành công',
  },
}

export function translateConsoleAccount(locale: AppLocale, key: string) {
  return packs[locale][key as AccountCopyKey] ?? key
}
