import { expect, test, type Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { installMockApi } from './mock-api'

const api = process.env.PARTOKENS_ROUTE_TEST_API || 'http://127.0.0.1:8082'
const evidence = process.env.PARTOKENS_ROUTE_TEST_EVIDENCE || '../../dogfood-output/2026-09-11-group-route-inline'
const headers = { Authorization: 'Bearer root-token' }

async function setup(page: Page) {
  const reset = await page.request.post(`${api}/__test/reset`)
  expect(reset.ok()).toBeTruthy()
  await installMockApi(page, { role: 100 })
  await page.route('**/admin-api/**', async (route) => {
    const path = new URL(route.request().url()).pathname.replace('/admin-api', '')
    const response = await route.fetch({ url: `${api}${path}`, headers: { ...route.request().headers(), ...headers } })
    await route.fulfill({ response })
  })
  await page.goto('/zh-CN/console/admin/routes')
  await expect(page.getByRole('table', { name: '分组路由总览' })).toBeVisible()
}

async function save(page: Page) {
  await page.getByRole('button', { name: '预览变更', exact: true }).click()
  const dialog = page.getByRole('dialog').last()
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: '确认保存', exact: true }).click()
  return dialog
}

async function addChannel(page: Page, name: string) {
  await page.getByRole('button', { name: '添加渠道', exact: true }).click()
  const selector = page.getByRole('button', { name: '选择渠道', exact: true }).last()
  await expect(selector).toBeFocused()
  await selector.click()
  await expect(page.getByRole('combobox', { name: '搜索渠道' })).toBeFocused()
  await page.getByRole('combobox', { name: '搜索渠道' }).fill(name)
  await page.getByRole('option').filter({ has: page.getByText(name, { exact: true }) }).click()
  await expect(page.getByRole('textbox', { name: '搜索已绑定渠道' })).toHaveValue('')
}

test('blank rows, unavailable options, duplicate prevention, reselect and local-only edits', async ({ page }) => {
  await setup(page)
  const writes: string[] = []
  page.on('request', (request) => { if (request.url().includes('/admin-api/') && request.method() !== 'GET') writes.push(request.url()) })
  await page.getByRole('button', { name: '配置 empty', exact: true }).click()
  await page.getByRole('button', { name: '添加渠道' }).click()
  await expect(page.locator('[data-route-row]')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '选择渠道', exact: true })).toBeFocused()
  await expect(page.getByRole('spinbutton', { name: '未选择渠道 优先级' })).toHaveValue('1000')
  await expect(page.getByRole('spinbutton', { name: '未选择渠道 权重' })).toHaveValue('100')
  await expect(page.getByRole('alert')).toContainText('尚未选择渠道')
  await expect(page.getByRole('button', { name: '预览变更' })).toBeDisabled()
  await page.getByRole('button', { name: '选择渠道', exact: true }).click()
  for (const [name, reason] of [['停用渠道', '渠道已停用'], ['无模型渠道', '渠道没有模型'], ['未就绪渠道', '渠道尚未就绪']]) {
    const option = page.getByRole('option').filter({ hasText: name })
    await expect(option).toBeDisabled()
    await expect(option).toContainText(reason!)
    await expect(option).toContainText('个模型')
  }
  const search = page.getByRole('combobox', { name: '搜索渠道' })
  await search.fill('missing-channel')
  await expect(page.getByText('没有匹配的渠道')).toBeVisible()
  await search.fill('渠道 A')
  await search.press('ArrowDown')
  await search.press('Enter')
  await expect(page.locator('[data-route-binding="lc_0"]')).toContainText('4 个模型')
  await page.getByRole('spinbutton', { name: '渠道 A 权重' }).fill('37')
  await page.getByRole('spinbutton', { name: '渠道 A 优先级' }).fill('-27')
  await addChannel(page, '渠道 B')
  await page.getByRole('button', { name: '重新选择渠道 渠道 B' }).click()
  await expect(page.getByRole('option').filter({ hasText: '渠道 A' })).toBeDisabled()
  await expect(page.getByRole('option').filter({ hasText: '渠道 A' })).toContainText('已在当前分组绑定或选中')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '重新选择渠道 渠道 A' }).click()
  await search.fill('渠道 C')
  await search.press('ArrowDown')
  await search.press('Enter')
  await expect(page.getByRole('spinbutton', { name: '渠道 C 权重' })).toHaveValue('37')
  await expect(page.getByRole('spinbutton', { name: '渠道 C 优先级' })).toHaveValue('-27')
  await expect(page.getByRole('spinbutton', { name: '渠道 B 优先级' })).toHaveValue('1000')
  await page.getByRole('spinbutton', { name: '渠道 C 优先级' }).fill('')
  await expect(page.getByRole('spinbutton', { name: '渠道 C 优先级' })).toHaveValue('')
  await expect(page.getByRole('alert')).toContainText('优先级必须')
  await page.getByRole('spinbutton', { name: '渠道 C 优先级' }).fill('-27')
  await page.getByRole('spinbutton', { name: '渠道 C 权重' }).fill('')
  await expect(page.getByRole('spinbutton', { name: '渠道 C 权重' })).toHaveValue('')
  await expect(page.getByRole('alert')).toContainText('权重必须')
  await page.getByRole('button', { name: '移除绑定 渠道 C' }).click()
  await page.getByRole('button', { name: '添加渠道' }).click()
  await page.locator('[data-slot="sheet-content"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: '保留草稿并离开' }).click()
  await page.getByRole('button', { name: '配置 empty', exact: true }).click()
  await expect(page.locator('[data-route-row]')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '预览变更' })).toBeDisabled()
  await page.getByRole('button', { name: '移除绑定 未选择渠道' }).click()
  await page.getByRole('button', { name: '移除绑定 渠道 B' }).click()
  await expect(page.locator('[data-route-row]')).toHaveCount(0)
  expect(writes).toEqual([])
})

async function assertLayout(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  const overflows = await page.locator('[data-route-binding], [data-route-group], [role="dialog"]').evaluateAll((elements) => elements.filter((element) => element.scrollWidth > element.clientWidth + 1).map((element) => element.getAttribute('data-route-binding') || element.getAttribute('data-route-group') || 'dialog'))
  expect(overflows).toEqual([])
}

test('overview includes empty groups, sorts tags, searches and preserves independent drafts', async ({ page }) => {
  await setup(page)
  await expect(page.locator('[data-route-group]')).toHaveCount(4)
  await expect(page.locator('[data-route-group="empty"]')).toContainText('未配置')
  const plus = page.locator('[data-route-group="plus"]')
  await expect(page.getByRole('columnheader', { name: '渠道', exact: true })).toBeVisible()
  expect(await plus.locator('[data-slot="badge"]').allTextContents()).toEqual(['渠道 B0.123x1234', '渠道 A0.123x1234', '渠道 C0.123x789'])
  await plus.getByRole('button', { name: '更多 2' }).click()
  await expect(plus).toContainText('long-channel-name')
  await expect(plus.locator('[data-slot="badge"]').last()).toContainText('未登记')
  await page.getByRole('textbox', { name: '搜索分组或渠道' }).fill('empty')
  await expect(page.locator('[data-route-group]')).toHaveCount(1)
  await page.getByRole('textbox', { name: '搜索分组或渠道' }).fill('')
  await page.getByRole('button', { name: '配置 plus', exact: true }).click()
  await page.getByRole('spinbutton', { name: '渠道 A 优先级', exact: true }).fill('1555')
  await page.locator('[data-slot="sheet-content"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: '保留草稿并离开' }).click()
  await page.getByRole('button', { name: '配置 empty', exact: true }).click()
  await page.locator('[data-slot="sheet-content"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: '配置 plus', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: '渠道 A 优先级', exact: true })).toHaveValue('1555')
  await page.request.post(`${api}/__test/control`, { data: { conflict: true } })
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await page.getByRole('button', { name: '预览变更' }).click()
  await expect(page.getByRole('alert').first()).toContainText('分组配置已变化')
  await expect(page.getByRole('spinbutton', { name: '渠道 A 优先级' })).toHaveValue('1555')
  await assertLayout(page)
})

test('inline additions, validation, model summary, save preview and real backend verification', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: '配置 empty', exact: true }).click()
  await addChannel(page, '渠道 A')
  await addChannel(page, '渠道 B')
  await expect(page.getByRole('spinbutton', { name: '渠道 A 优先级' })).toHaveValue('1000')
  await expect(page.locator('[data-route-binding="lc_0"]')).toContainText('50.0%')
  await expect(page.locator('[data-route-binding="lc_0"]')).toContainText('0.123x')
  const summary = page.locator('[data-route-binding="lc_0"] summary')
  await expect(summary).toContainText('可用 1')
  await expect(summary).toContainText('异常 1')
  await expect(summary).toContainText('未测试 1')
  await expect(summary).toContainText('测试中 1')
  await summary.click()
  await expect(page.locator('[data-route-binding="lc_0"]')).toContainText('running-model')
  await page.getByRole('spinbutton', { name: '渠道 A 权重' }).fill('0')
  await expect(page.getByRole('button', { name: '预览变更' })).toBeDisabled()
  await page.getByRole('spinbutton', { name: '渠道 A 权重' }).fill('75')
  await page.getByRole('spinbutton', { name: '渠道 A 优先级' }).fill('1729')
  const dialog = await save(page)
  await expect(dialog).toContainText('新增绑定')
  await expect(dialog.getByRole('heading')).toHaveText('empty · 已保存')
  const response = await page.request.get(`${api}/v1/routes`, { headers })
  const route = (await response.json()).data.find((item: { group_name: string }) => item.group_name === 'empty')
  expect(route.config.layers).toEqual([{ priority: 1729, members: [{ logical_id: 'lc_0', weight: 75 }] }, { priority: 1000, members: [{ logical_id: 'lc_1', weight: 100 }] }])
  await dialog.getByRole('button', { name: '完成', exact: true }).click()
  await expect(page.getByRole('button', { name: '重新选择渠道 渠道 A' })).toHaveCount(0)
  await expect(page.getByRole('spinbutton', { name: '渠道 A 优先级' })).toHaveValue('1729')
  await expect(page.locator('[data-route-group="empty"]')).toContainText('已配置')
  await assertLayout(page)
})

test('manual priorities and retry limits, partial failure resumes, clearing is separately confirmed', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: '配置 empty', exact: true }).click()
  for (const name of ['渠道 A', '渠道 B']) await addChannel(page, name)
  await page.getByRole('spinbutton', { name: '渠道 A 优先级' }).fill('900')
  await expect(page.getByRole('spinbutton', { name: '渠道 B 优先级' })).toHaveValue('1000')
  await expect(page.getByRole('spinbutton', { name: '渠道 A 优先级' })).toHaveValue('900')
  for (const [name, priority] of [['渠道 C', '800'], ['渠道 D', '700']]) {
    await addChannel(page, name!)
    await page.getByRole('spinbutton', { name: `${name} 优先级` }).fill(priority!)
  }
  await expect(page.getByRole('alert')).toContainText('4 个优先级超过')
  await page.getByRole('button', { name: '移除绑定 渠道 D' }).click()
  await page.request.post(`${api}/__test/control`, { data: { fail_once: true } })
  const dialog = await save(page)
  await expect(dialog).toContainText('部分失败')
  await expect(dialog.getByRole('button', { name: '继续执行', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: '继续执行', exact: true }).click()
  await expect(dialog.getByRole('heading')).toHaveText('empty · 已保存')
  await dialog.getByRole('button', { name: '完成' }).click()
  for (const name of ['渠道 A', '渠道 B', '渠道 C']) await page.getByRole('button', { name: `移除绑定 ${name}` }).click()
  await page.getByRole('button', { name: '预览变更' }).click()
  await expect(page.getByRole('dialog')).toContainText('没有受本系统管理的路由渠道')
  await page.getByRole('button', { name: '确认清空并预览' }).click()
  await expect(page.getByRole('dialog')).toContainText('保存后将无渠道覆盖')
  await page.getByRole('button', { name: '确认保存' }).click()
  await expect(page.getByRole('heading', { name: 'empty · 已保存' })).toBeVisible()
  await page.getByRole('button', { name: '完成' }).click()
  await expect(page.locator('[data-route-group="empty"]')).toContainText('未配置')
  const routes = (await (await page.request.get(`${api}/v1/routes`, { headers })).json()).data
  expect(routes.find((item: { group_name: string }) => item.group_name === 'other').revision).toBe(1)
})

test('nonstandard channels appear in preview despite stale monitor and require fresh acknowledgment', async ({ page }) => {
  await setup(page)
  await page.request.post(`${api}/__test/control`, { data: { nonstandard: true } })
  await page.getByRole('button', { name: '配置 empty', exact: true }).click()
  await addChannel(page, '渠道 A')
  await page.getByRole('button', { name: '预览变更', exact: true }).click()
  const dialog = page.getByRole('dialog').last()
  const acknowledge = dialog.getByRole('checkbox', { name: '我已核对并确认保留以上非标准物理渠道' })
  const confirm = dialog.getByRole('button', { name: '确认保存', exact: true })
  await expect(dialog).toContainText('#900 · 旧版共享渠道 · 启用')
  await expect(dialog).not.toContainText('其他分组旧渠道')
  await expect(confirm).toBeDisabled()
  await acknowledge.check()
  await expect(confirm).toBeEnabled()
  await acknowledge.uncheck()
  await expect(confirm).toBeDisabled()
  await acknowledge.check()
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '预览变更', exact: true }).click()
  await expect(acknowledge).not.toBeChecked()
  await expect(confirm).toBeDisabled()
  await acknowledge.check()
  await confirm.click()
  await expect(dialog.getByRole('heading')).toHaveText('empty · 已保存')
})

test('background refresh retains drafts and navigation requires a decision', async ({ page }) => {
  await page.clock.install()
  await setup(page)
  await page.getByRole('button', { name: '配置 plus', exact: true }).click()
  await page.getByRole('spinbutton', { name: '渠道 A 权重' }).fill('77')
  await page.request.post(`${api}/__test/control`, { data: { conflict: true } })
  await page.clock.fastForward(61000)
  await expect(page.getByRole('alert')).toContainText('后台配置已更新')
  await expect(page.getByRole('spinbutton', { name: '渠道 A 权重' })).toHaveValue('77')
  await expect(page.getByRole('button', { name: '预览变更' })).toBeDisabled()
  await page.locator('[data-slot="sheet-content"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: '保留草稿并离开' }).click()
  await page.getByRole('link', { name: '渠道', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('离开分组路由')
  await page.getByRole('button', { name: '继续编辑', exact: true }).click()
  await page.getByRole('button', { name: '配置 plus', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: '渠道 A 权重' })).toHaveValue('77')
  await page.getByRole('button', { name: '核对最新配置' }).click()
  await page.getByRole('button', { name: '载入最新配置' }).click()
  await expect(page.getByRole('spinbutton', { name: '渠道 A 权重' })).toHaveValue('50')
})

test('stale save preview reports conflict and keeps the edited numbers', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: '配置 plus', exact: true }).click()
  await page.getByRole('spinbutton', { name: '渠道 A 权重' }).fill('83')
  await page.getByRole('button', { name: '预览变更' }).click()
  await page.request.post(`${api}/__test/control`, { data: { conflict: true } })
  await page.getByRole('button', { name: '确认保存' }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('分组配置已变化')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: '渠道 A 权重' })).toHaveValue('83')
})

test('mobile supports inline selection, preview and verified save', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setup(page)
  await page.getByRole('button', { name: '配置 empty', exact: true }).click()
  await addChannel(page, '渠道 A')
  await page.getByRole('spinbutton', { name: '渠道 A 优先级' }).fill('2026')
  await page.getByRole('button', { name: '预览变更' }).click()
  const review = page.getByRole('dialog').last()
  await expect(review).toContainText('优先级 2026')
  await assertLayout(page)
  await page.screenshot({ path: `${evidence}/preview-390.png`, fullPage: true })
  await review.getByRole('button', { name: '确认保存' }).click()
  await expect(page.getByRole('heading', { name: 'empty · 已保存' })).toBeVisible()
  await review.getByRole('button', { name: '完成' }).click()
  await expect(page.getByRole('spinbutton', { name: '渠道 A 优先级' })).toHaveValue('2026')
})

for (const width of [1440, 1024, 390, 320]) {
  test(`layout at ${width}px with long channel names and model details`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await setup(page)
    await mkdir(evidence, { recursive: true })
    await page.locator('[data-route-group="plus"]').getByRole('button', { name: '更多 2' }).click()
    await assertLayout(page)
    await page.screenshot({ path: `${evidence}/overview-${width}.png`, fullPage: true })
    await page.getByRole('button', { name: '配置 plus', exact: true }).click()
    const sheet = page.locator('[data-slot="sheet-content"]')
    await expect(sheet).toBeVisible()
    await expect(sheet).toHaveCSS('right', '0px')
    await expect(sheet).toHaveCSS('height', '900px')
    const previewButton = sheet.getByRole('button', { name: /预览变更|重建执行渠道/ })
    await expect(previewButton).toBeInViewport()
    await page.locator('[data-route-binding="lc_0"] summary').click()
    await expect(page.locator('[data-route-binding="lc_6"]')).toContainText('未登记')
    await assertLayout(page)
    await expect(previewButton).toBeInViewport()
    await page.screenshot({ path: `${evidence}/editor-${width}.png`, fullPage: true })
    await page.getByRole('button', { name: '添加渠道' }).click()
    await page.getByRole('button', { name: '选择渠道', exact: true }).click()
    await expect(page.getByRole('option').filter({ hasText: '渠道 A' })).toBeDisabled()
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: '移除绑定 未选择渠道' }).click()
    await sheet.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: '配置 empty', exact: true }).click()
    for (let index = 0; index < 8; index++) {
      await page.getByRole('button', { name: '添加渠道' }).click()
      await expect(page.getByRole('button', { name: '选择渠道', exact: true }).last()).toBeFocused()
      await expect(page.getByRole('button', { name: '选择渠道', exact: true }).last()).toBeInViewport()
    }
    await expect(page.locator('[data-route-row]')).toHaveCount(8)
    await expect(sheet.getByRole('heading')).toBeInViewport()
    await expect(previewButton).toBeInViewport()
    await page.getByRole('button', { name: '选择渠道', exact: true }).last().click()
    const menu = page.locator('[data-slot="popover-content"]')
    await expect(menu).toBeInViewport({ ratio: 1 })
    await assertLayout(page)
    await page.screenshot({ path: `${evidence}/selector-${width}.png`, fullPage: true })
    await page.getByRole('combobox', { name: '搜索渠道' }).fill('long-channel')
    await page.getByRole('combobox', { name: '搜索渠道' }).press('ArrowDown')
    await page.getByRole('combobox', { name: '搜索渠道' }).press('Enter')
    const longRow = page.locator('[data-route-binding="lc_6"]')
    await expect(longRow).toContainText('160 个模型')
    await longRow.locator('summary').click()
    await expect(longRow.locator('details')).toHaveAttribute('open', '')
    await assertLayout(page)
    const overlaps = await longRow.locator('input, button').evaluateAll((controls) => controls.flatMap((control, index) => {
      const a = control.getBoundingClientRect()
      return controls.slice(index + 1).filter((other) => { const b = other.getBoundingClientRect(); return Math.min(a.right, b.right) - Math.max(a.left, b.left) > 1 && Math.min(a.bottom, b.bottom) - Math.max(a.top, b.top) > 1 }).map((other) => `${control.getAttribute('aria-label')} / ${other.getAttribute('aria-label')}`)
    }))
    expect(overlaps).toEqual([])
    await page.screenshot({ path: `${evidence}/drafts-${width}.png`, fullPage: true })
  })
}
